/*
 * Generated by Phase-2B WP4 codec_stub.
 * Deterministic. No timestamps.
 *
 * Control bus: &i2c18 (SoC QUP i2c controller — confirmed by T4a.qup.*).
 * DAI-cells: <0> per codec (both are single-DAI devices).
 */

#include <linux/i2c.h>
#include <linux/module.h>

/* ADI ADAU1979 quad-ADC (mic capture) */
static struct i2c_board_info nord_adau1979_info = {
	.type = "adau1979",
	.addr = 0x31,
	/* compatible = "adi,adau1979" */
};

/* TI PCM1681 8-channel DAC (speaker feed) */
static struct i2c_board_info nord_pcm1681_info = {
	.type = "pcm1681",
	.addr = 0x4c,
	/* compatible = "ti,pcm1681" */
};

/*
 * Reviewer TODO — board-side signals not resolvable from IPCAT:
 *
 *   FIXME(reset-gpios): codec reset line — pin # varies per board revision
 *   FIXME(ADC_MCLK): shared MCLK feed for the ADAU1979 — sourced from LPASS or crystal, board-specific
 *   FIXME(GLOBAL_MD_OE): codec-domain output-enable line — schematic net, no IPCAT authority
 */
