"""Phase-2B WP3 — DT scaffolding generator (first generator lane).

Pure, stdlib-only DT-scaffolding generator. Consumes a WP2-projected
``TrustedFacts`` and emits either a ``GeneratedArtifact`` carrying DTSI text
(as raw bytes) or a ``GeneratorSkipped`` when the gates are closed.

The DT scaffolding is the *first* artifact class in
``_GENERATION_ARTIFACT_ORDER``. It exists to unblock a downstream reviewer's
work: given a Nord target with clean T1 (I2S pinmux) and T5 (firmware +
compatible) verdicts, this generator emits an ``sound.dtsi`` fragment that
declares the I2S pin group and the SoC-family firmware compatible string.
Anything else (codec DAI-link, machine-driver bindings, AudioReach topology)
lands in later WPs (WP4–WP6).

Gating (per PHASE2B_SPECIFICATION.md §4.1 + §WP3):

  1. **Known-bad donor residue check (§4.4) — runs first.**
     If ``T5.dts.firmware`` is ``PARTIAL_MATCH`` with a ``rule_id`` inside
     ``KNOWN_BAD_PARTIAL_MATCH_RULES`` (as of v1.0: exactly the sa8775p Eliza
     donor residue), the generator refuses. Emitting a PARTIAL_MATCH-open DTS
     here would bake the donor firmware path into a Nord artifact — this is
     exactly the defect class Phase-2A caught, now guarded at the generator.

  2. **T5.dts.firmware gate must be OPEN** (or PARTIAL_MATCH-open with a
     non-known-bad rule_id). Falling through here means either the row is
     missing (``authority_not_in_snapshot``) or the row carries a closed
     verdict (``DISAGREE_WITH_AUTHORITY`` / ``NOT_CROSS_CHECKABLE`` /
     ``REVIEW_REQUIRED``) — no firmware path, no artifact.

  3. **T5.dts.compatible gate must be OPEN.** Firmware alone is insufficient;
     the compatible string identifies the SoC-family this DTS targets.

  4. **T1 pins (per-pin granularity, per §4.1).** The gating expression
     ``("T1", "gpio.i2s.*")`` is satisfied file-wise as long as *some* pin is
     open; individual pins that are missing become ``FIXME(<pin>)`` markers
     in the emitted bytes AND contribute a partial-artifact
     ``NOT_CROSS_CHECKABLE`` row to ``contributes_rows``. Pins that ARE open
     emit real declarations.

Header comment discipline (§4.4): when ``T5.dts.firmware`` is ``PARTIAL_MATCH``
with a *non-known-bad* rule_id (gate opens, but the reviewer needs to see the
rule_id before merge), a fixed machine-parseable header comment block is
prepended to ``bytes_`` so downstream tooling can grep the artifact for
outstanding review actions.

Zero I/O, zero timestamps, zero env reads. Byte-identical input → byte-
identical output.

Import discipline (WP3):

  * MAY import: ``orchestrator.generation.model`` (WP1a — the four
    dataclasses) and ``orchestrator.generation.config`` (WP1b — policy
    constants: ``GATING_ROWS``, ``KNOWN_BAD_PARTIAL_MATCH_RULES``,
    ``PATH_GUARD_ROOT``); ``orchestrator.reasoning.crossverify_model``
    (``VerificationRow`` type — needed to append partial-artifact rows to
    ``contributes_rows``).
  * MUST NOT import: ``orchestrator.generation.facts`` (WP3 *receives*
    ``TrustedFacts`` as input — it does not call ``project_facts`` itself,
    that composition happens at the runner layer);
    ``orchestrator.reasoning.crossverify`` or
    ``orchestrator.reasoning.cardinality`` (Phase-2A internals).
  * Enforced by ``tests/test_generation_dt.py::test_import_guard``.

Run the tests: ``PYTHONPATH=audio_bu_skill python3 -m tests.test_generation_dt``
"""

from __future__ import annotations

from orchestrator.generation.config import (
    KNOWN_BAD_PARTIAL_MATCH_RULES,
    PATH_GUARD_ROOT,
)
from orchestrator.generation.model import (
    GeneratedArtifact,
    GeneratorSkipped,
    GenerationResult,
    TrustedFacts,
)
from orchestrator.reasoning.crossverify_model import VerificationRow

# ── Constants ───────────────────────────────────────────────────────────────

#: Canonical I2S pin set. Iterated in this fixed order so the generated bytes
#: are deterministic. Missing pins become ``FIXME(<pin>)`` markers; present
#: pins emit real declarations. Extending this tuple is an intentional spec
#: change to WP3 — the byte-frozen fixture will drift.
_REQUIRED_I2S_PINS: tuple[str, ...] = ("mclk", "bclk", "lrclk", "dout")

#: The artifact class this generator emits. Fixed — matches the WP1b
#: ``_GENERATION_ARTIFACT_ORDER`` first entry.
_ARTIFACT_CLASS: str = "dt_scaffolding"

#: The gating rows this generator inspects, in the exact order the spec
#: enumerates them (§4.1). Used verbatim in ``GeneratorSkipped.gating_rows``
#: so a skipped verdict names its closed gates in a stable order.
_GATING_ROW_NAMES: tuple[str, ...] = (
    "T1.gpio.i2s.*",
    "T5.dts.firmware",
    "T5.dts.compatible",
)


def generate_dt(facts: TrustedFacts, kb: object | None = None) -> GenerationResult:
    """Emit a DT scaffolding artifact or a skipped verdict for one target.

    Pure, deterministic, zero I/O. Byte-identical ``facts.to_dict()`` produces
    byte-identical ``result.to_dict()`` (modulo ``bytes_hex``).

    Parameters
    ----------
    facts:
        Immutable projection of a target's Phase-2A verification rows
        (produced by ``orchestrator.generation.facts.project_facts``).
    kb:
        Optional knowledge-base handle (WP4+ uses this for rule lookup). WP3
        does not consult a KB — the ``rule_id`` field on gating rows is the
        entire policy signal. Accepted for future symmetry so all generators
        share the same ``(facts, kb)`` signature.

    Returns
    -------
    GenerationResult
        Either a ``GeneratedArtifact`` (bytes + contributes_rows) or a
        ``GeneratorSkipped`` naming its closed gates.

    The ``subject`` field on the returned dataclass is the fixed literal
    ``"dt_scaffolding"`` — matching ``artifact_class`` — because WP3 emits
    one artifact per target, not one per pin.
    """
    del kb  # WP3 does not consult a KB — see docstring.

    firmware_row = facts.rows_by_track_subject.get("T5.dts.firmware")

    # ── Gate 1: known-bad donor residue (§4.4) — runs first ─────────────────
    # A PARTIAL_MATCH row whose rule_id is in the known-bad set MUST route
    # to skipped BEFORE the "is gate open" check considers it open.
    if (
        firmware_row is not None
        and firmware_row.verdict == "PARTIAL_MATCH"
        and firmware_row.rule_id in KNOWN_BAD_PARTIAL_MATCH_RULES
    ):
        return GeneratorSkipped(
            subject=_ARTIFACT_CLASS,
            artifact_class=_ARTIFACT_CLASS,
            reason="gating_row_partial_match_donor_residue",
            gating_rows=["T5.dts.firmware"],
        )

    # ── Gate 2: T5.dts.firmware open (MATCH or non-known-bad PARTIAL_MATCH) ─
    if not facts.is_open("T5", "dts.firmware"):
        # Row missing entirely: authority not in snapshot.
        if firmware_row is None:
            return GeneratorSkipped(
                subject=_ARTIFACT_CLASS,
                artifact_class=_ARTIFACT_CLASS,
                reason="authority_not_in_snapshot",
                gating_rows=["T5.dts.firmware"],
            )
        # Row present but gate closed for a warning/verdict reason. Pick the
        # most-specific skip reason: warning=True → gating_row_warning;
        # verdict REVIEW_REQUIRED → gating_row_review_required; verdict
        # DISAGREE_WITH_AUTHORITY → gating_row_disagree; otherwise
        # gating_row_warning as a catch-all.
        return GeneratorSkipped(
            subject=_ARTIFACT_CLASS,
            artifact_class=_ARTIFACT_CLASS,
            reason=_skip_reason_for_closed_gate(firmware_row),
            gating_rows=["T5.dts.firmware"],
        )

    # ── Gate 3: T5.dts.compatible open ──────────────────────────────────────
    compatible_row = facts.rows_by_track_subject.get("T5.dts.compatible")
    if not facts.is_open("T5", "dts.compatible"):
        if compatible_row is None:
            return GeneratorSkipped(
                subject=_ARTIFACT_CLASS,
                artifact_class=_ARTIFACT_CLASS,
                reason="authority_not_in_snapshot",
                gating_rows=["T5.dts.compatible"],
            )
        return GeneratorSkipped(
            subject=_ARTIFACT_CLASS,
            artifact_class=_ARTIFACT_CLASS,
            reason=_skip_reason_for_closed_gate(compatible_row),
            gating_rows=["T5.dts.compatible"],
        )

    # ── Gates open — build the artifact ─────────────────────────────────────
    lines: list[str] = []

    # Header comment discipline (§4.4): non-known-bad PARTIAL_MATCH firmware
    # gate → machine-parseable comment naming the rule_id. Emitted so a
    # downstream grep for ``PARTIAL_MATCH gate`` surfaces every artifact that
    # opened on a KB-downgraded verdict.
    if firmware_row.verdict == "PARTIAL_MATCH":
        lines.append(
            f"// PARTIAL_MATCH gate: T5.dts.firmware (rule_id={firmware_row.rule_id})"
        )
        lines.append(
            "//   The row matched on family but a KB rule downgraded"
        )
        lines.append(
            "//   the verdict to PARTIAL_MATCH; the reviewer must"
        )
        lines.append(
            "//   confirm firmware before this artifact is merged."
        )

    # Fixed DTS preamble. No target-name interpolation — the subject
    # ``dt_scaffolding`` is the only variable, and it is fixed here.
    lines.append("/*")
    lines.append(" * Generated by Phase-2B WP3 dt_scaffolding.")
    lines.append(" * Deterministic. No timestamps.")
    lines.append(" */")
    lines.append("")
    lines.append("&i2s_primary {")

    # Emit pin declarations in fixed lexicographic order. Missing pins get
    # a FIXME marker AND a partial-artifact contributes_rows entry.
    contributes_rows: list[VerificationRow] = []
    for pin in _REQUIRED_I2S_PINS:
        pin_row = facts.rows_by_track_subject.get(f"T1.gpio.i2s.{pin}")
        if pin_row is not None and pin_row.verdict == "MATCH" and not pin_row.warning:
            lines.append(f"\tpinctrl-i2s-{pin}: {pin};")
        else:
            # Missing / warning / non-MATCH → FIXME + partial-artifact row.
            lines.append(f"\tpinctrl-i2s-{pin}: FIXME({pin});")
            contributes_rows.append(
                VerificationRow(
                    track="T1",
                    subject=f"gpio.i2s.{pin}",
                    verdict="NOT_CROSS_CHECKABLE",
                    coverage_gap_reason="authority_out_of_scope",
                    notes=[
                        f"dt_scaffolding: pin {pin!r} not in snapshot — "
                        "FIXME marker emitted; reviewer must confirm."
                    ],
                )
            )

    lines.append("};")
    lines.append("")

    # Emit the compatible declaration. Fixed literal — Phase-2A verified
    # T5.dts.compatible is MATCH, so the value is downstream-committed.
    lines.append("&adsp {")
    lines.append("\tcompatible = \"qcom,adsp\";")
    lines.append("};")

    # Trailing newline — LF line endings, no BOM. Exactly one LF at EOF.
    bytes_ = ("\n".join(lines) + "\n").encode("utf-8")

    return GeneratedArtifact(
        subject=_ARTIFACT_CLASS,
        artifact_class=_ARTIFACT_CLASS,
        path_hint=f"{PATH_GUARD_ROOT}{_ARTIFACT_CLASS}/sound.dtsi",
        bytes_=bytes_,
        contributes_rows=contributes_rows,
    )


def _skip_reason_for_closed_gate(row: VerificationRow) -> str:
    """Map a closed row to its most-specific WP1b skip reason.

    Not exhaustive over ``SKIP_REASONS`` — WP3 only emits the four reasons
    below (donor-residue is handled inline above; ``authority_not_in_snapshot``
    is emitted when the row is *missing*, not closed). The specialised
    ``gating_row_disagree_on_bus`` / ``…_on_lpass_count`` /
    ``…_ambiguous_soundwire`` reasons belong to later WPs (WP4/WP5/WP6) whose
    subject vocabulary distinguishes them.
    """
    if row.verdict == "REVIEW_REQUIRED":
        return "gating_row_review_required"
    if row.verdict == "DISAGREE_WITH_AUTHORITY":
        return "gating_row_disagree"
    # warning=True with a verdict that isn't the two above (e.g. an explicit
    # warning override on MATCH/PARTIAL_MATCH) → gating_row_warning.
    return "gating_row_warning"


__all__ = ["generate_dt"]
